"""
Django settings for styleguide_example project.

Generated by 'django-admin startproject' using Django 3.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""
import environ
import os
from config.env import BASE_DIR, env


environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^kb+hpmf4#c-d$&84qn@yr&geqj90n@sad4j!rofoqasg14xm='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DJANGO_DEBUG", default=True)

ALLOWED_HOSTS = ["*"]


# Application definition
LOCAL_APPS = [
    'mp.common.apps.CommonConfig',
    'mp.users.apps.UsersConfig',
    'mp.audit.apps.AuditConfig',
    'mp.assets.apps.AssetsConfig',
    'mp.apps.apps.AppsConfig',
    'mp.links.apps.LinksConfig',
    'mp.workflow.apps.WorkflowConfig',
    'mp.api.apps.ApiConfig',
]


THIRD_PARTY_APPS = [
    "rest_framework",
    "django_filters",
    'django_q',
    'geoposition',
    "corsheaders",
    # jwt auth
    "rest_framework_jwt",
    'rest_framework_jwt.blacklist',
]

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    *THIRD_PARTY_APPS,
    *LOCAL_APPS,
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "config.middleware.check_login_middleware.JSONWebTokenMiddleware"
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, 'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    "default": env.db("DATABASE_URL", default="mysql:///127.0.0.1"),
}
DATABASES["default"]["ATOMIC_REQUESTS"] = True


# Cache  4.0 默认增加了RedisCache
CACHES = {
    "default": env.cache('CACHE_URL', default="redis://127.0.0.1/0")
}
# CACHES["default"]["OPTIONS"] = {"CLIENT_CLASS": "django_redis.client.DefaultClient"}

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True

# 时间格式化
USE_L10N = False  # 默认True
DATETIME_FORMAT = 'Y-m-d H:i:s'
DATE_FORMAT = 'Y-m-d'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'mp/static')]
STATIC_ROOT = os.path.join(BASE_DIR, "static")

# 媒体静态文件
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media').replace('\\', '/') + '/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# login
LOGIN_URL = '/user/login/'
LOGIN_REDIRECT_URL = env.str('LOGIN_REDIRECT_URL', default="/")
LOGOUT_REDIRECT_URL = env.str('LOGIN_URL', default=LOGIN_URL)  # 注销重定向页面

# custom user model
AUTH_USER_MODEL = 'users.MyUser'
AUTHENTICATION_BACKENDS = [
    # 拒绝不活跃用户(is_active)
    # 'django.contrib.auth.backends.ModelBackend',
    'config.backends.auth_backends.MyBackend',
]
# APP_DOMAIN = env("APP_DOMAIN", default="http://localhost:8000")

from config.settings.q import Q_CLUSTER  # noqa
from config.settings.sessions import *  # noqa
from config.settings.logs import *  # noqa
from config.settings.rest import *  # noqa
from config.settings.custom import *  # noqa
from config.settings.jwt import *  # noqa
from config.settings.cors import *  # noqa

