# Generated by Django 4.2 on 2023-06-21 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0003_sshuser_created_at_sshuser_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='组名称')),
                ('desc', models.CharField(blank=True, max_length=150, null=True, verbose_name='描述')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='apps.resourcegroup', verbose_name='上级')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
            ],
            options={
                'verbose_name': '业务组管理',
                'verbose_name_plural': '业务组管理',
                'db_table': 'mp_apps_group',
                'permissions': (('add_resource_group', '添加业务组'), ('change_resource_group', '修改业务组'), ('delete_resource_group', '删除业务组'), ('view_resource_group', '查看业务组')),
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Apps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='应用名称')),
                ('env', models.CharField(choices=[('pro', '生产环境'), ('dev', '测试环境')], default='pro', max_length=10, verbose_name='环境')),
                ('develop_user', models.CharField(blank=True, max_length=20, verbose_name='开发负责人')),
                ('deploy_user', models.CharField(blank=True, max_length=20, verbose_name='运维负责人')),
                ('deploy_path', models.CharField(max_length=255, verbose_name='部署路径')),
                ('deploy_mode', models.CharField(choices=[('docker', 'docker'), ('docker-compose', 'docker compose'), ('k8s', 'k8s'), ('local', '直接部署'), ('other', '其它方式')], default='docker-compose', max_length=20, verbose_name='部署方式')),
                ('up_date', models.DateField(blank=True, null=True, verbose_name='上线时间')),
                ('down_date', models.DateField(blank=True, null=True, verbose_name='到期时间')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('assets', models.ManyToManyField(blank=True, to='assets.serverassets', verbose_name='服务器')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.resourcegroup', verbose_name='所属部门')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='apps.apps', verbose_name='上级业务')),
            ],
            options={
                'verbose_name': '应用管理',
                'verbose_name_plural': '业务管理表',
                'db_table': 'mp_apps',
                'permissions': (('add_apps', '添加应用'), ('change_apps', '修改应用'), ('delete_apps', '删除应用'), ('view_apps', '查看应用')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='AppPorts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('start_port', models.PositiveIntegerField(verbose_name='启动端口')),
                ('map_port', models.PositiveIntegerField(verbose_name='映射端口')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('app', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='apps.apps')),
            ],
            options={
                'verbose_name': '应用端口',
                'verbose_name_plural': '应用端口',
                'db_table': 'mp_apps_port',
                'permissions': (('add_app_ports', '添加映射端口'), ('change_app_ports', '修改映射端口'), ('delete_app_ports', '删除映射端口'), ('view_app_ports', '查看映射端口')),
                'default_permissions': (),
            },
        ),
    ]
