# Generated by Django 4.2 on 2023-06-21 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_remove_resourcegroup_is_deleted_apps_is_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apps',
            options={'default_permissions': (), 'permissions': (('add_apps', '添加应用'), ('change_apps', '修改应用'), ('delete_apps', '删除应用'), ('view_apps', '查看应用')), 'verbose_name': '应用管理', 'verbose_name_plural': '业务管理'},
        ),
        migrations.AlterField(
            model_name='apps',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apps', to='apps.resourcegroup', verbose_name='所属部门'),
        ),
    ]
