# Generated by Django 4.2 on 2023-06-25 03:50

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_apps_options_alter_apps_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apps',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='apps.apps', verbose_name='上级应用'),
        ),
    ]
