# Generated by Django 4.2 on 2023-06-01 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='nickname',
            field=models.CharField(default='', max_length=50, null=True, unique=True, verbose_name='昵称'),
        ),
    ]
