# Generated by Django 4.2 on 2023-06-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_mygroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('user_name', models.CharField(max_length=30, null=True, verbose_name='用户名称')),
                ('user_display', models.CharField(max_length=50, null=True, verbose_name='用户中文名')),
                ('action', models.CharField(max_length=255, verbose_name='动作')),
                ('extra_info', models.TextField(null=True, verbose_name='额外的信息')),
                ('ip', models.GenericIPAddressField(null=True, verbose_name='登陆IP')),
                ('action_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
            ],
            options={
                'verbose_name': '登陆日志',
                'verbose_name_plural': '登陆日志',
                'db_table': 'mp_login_logs',
                'permissions': (('add_loginlogs', '添加登陆日志'), ('change_loginlogs', '修改审计日志'), ('delete_loginlogs', '删除审计日志'), ('view_loginlogs', '查看审计日志')),
                'managed': True,
                'default_permissions': (),
            },
        ),
    ]
