# Generated by Django 4.2 on 2023-06-25 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('work_name', models.CharField(max_length=50, verbose_name='名称')),
                ('work_user', models.CharField(max_length=30, verbose_name='发起人')),
                ('work_user_display', models.CharField(default='', max_length=50, verbose_name='发起人中文名')),
                ('app_group_id', models.IntegerField(verbose_name='组ID')),
                ('app_name', models.CharField(max_length=100, verbose_name='组名称')),
                ('work_type', models.SmallIntegerField(choices=[(0, '自动更新'), (1, '业务上线'), (2, '问题排查'), (3, '漏洞修复'), (4, '系统优化'), (5, '应用更新')], verbose_name='类型')),
                ('work_status', models.CharField(choices=[('finish', '正常结束'), ('abort', '终止流程'), ('manreviewing', '等待审核'), ('review_pass', '审核通过'), ('timingtask', '定时执行'), ('queuing', '排队中'), ('executing', '执行中'), ('autoreviewwrong', '审核不通过'), ('exception', '执行异常')], max_length=50, verbose_name='状态')),
                ('run_date_start', models.DateTimeField(blank=True, null=True, verbose_name='可执行起始时间')),
                ('run_date_end', models.DateTimeField(blank=True, null=True, verbose_name='可执行结束时间')),
            ],
            options={
                'verbose_name': '工作流',
                'verbose_name_plural': '工作流管理',
                'db_table': 'mp_workflow',
                'permissions': (('add_workflow', '添加工作流'), ('change_workflow', '修改工作流'), ('delete_workflow', '删除工作流'), ('view_workflow', '查看工作流')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='WorkflowLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('audit_id', models.IntegerField(db_index=True, verbose_name='工单审批id')),
                ('operation_type', models.SmallIntegerField(choices=[(0, '提交/待审核'), (1, '审核通过'), (2, '审核不通过'), (3, '审核取消'), (4, '定时执行'), (5, '执行工单'), (6, '执行结束')], verbose_name='操作类型')),
                ('operation_type_desc', models.CharField(max_length=10, verbose_name='操作类型描述')),
                ('operation_info', models.CharField(max_length=1000, verbose_name='操作信息')),
                ('operator', models.CharField(max_length=30, verbose_name='操作人')),
                ('operator_display', models.CharField(default='', max_length=50, verbose_name='操作人中文名')),
            ],
            options={
                'verbose_name': '工作流日志',
                'verbose_name_plural': '工作流日志',
                'db_table': 'mp_workflow_log',
            },
        ),
        migrations.CreateModel(
            name='WorkflowAuditLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('audit_id', models.AutoField(primary_key=True, serialize=False)),
                ('app_group_id', models.IntegerField(verbose_name='组ID')),
                ('app_group_name', models.CharField(max_length=100, verbose_name='组名称')),
                ('workflow_id', models.BigIntegerField(verbose_name='工单id')),
                ('workflow_type', models.IntegerField(choices=[(0, '自动更新'), (1, '业务上线'), (2, '问题排查'), (3, '漏洞修复'), (4, '系统优化'), (5, '应用更新')], verbose_name='申请类型')),
                ('workflow_title', models.CharField(max_length=50, verbose_name='申请标题')),
                ('workflow_remark', models.CharField(blank=True, default='', max_length=140, verbose_name='申请备注')),
                ('audit_auth_groups', models.CharField(max_length=255, verbose_name='审批权限组列表')),
                ('current_audit', models.CharField(max_length=20, verbose_name='当前审批权限组')),
                ('next_audit', models.CharField(max_length=20, verbose_name='下级审批权限组')),
                ('current_status', models.SmallIntegerField(choices=[(0, '待审核'), (1, '审核通过'), (2, '审核不通过'), (3, '审核取消')], verbose_name='审核状态')),
                ('create_user', models.CharField(max_length=30, verbose_name='申请人')),
                ('create_user_display', models.CharField(default='', max_length=50, verbose_name='申请人中文名')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('result', models.TextField(blank=True, null=True, verbose_name='执行结果')),
            ],
            options={
                'verbose_name': '工作流审批列表',
                'verbose_name_plural': '工作流审批列表',
                'db_table': 'mp_workflow_audit_log',
                'unique_together': {('workflow_id', 'workflow_type')},
            },
        ),
        migrations.CreateModel(
            name='WorkFlowAudit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('audit_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_id', models.IntegerField(verbose_name='组ID')),
                ('group_name', models.CharField(max_length=100, verbose_name='组名称')),
                ('workflow_type', models.SmallIntegerField(choices=[(0, '自动更新'), (1, '业务上线'), (2, '问题排查'), (3, '漏洞修复'), (4, '系统优化'), (5, '应用更新')], verbose_name='审批类型')),
                ('audit_auth_groups', models.CharField(max_length=255, verbose_name='审批权限组列表')),
            ],
            options={
                'verbose_name': '审批流程配置',
                'verbose_name_plural': '审批流程配置',
                'db_table': 'mp_workflow_audit',
                'unique_together': {('group_id', 'workflow_type')},
            },
        ),
    ]
