# Generated by Django 4.2 on 2023-06-26 01:33

from django.db import migrations, models
import mp.workflow.models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_alter_workflowaudit_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=mp.workflow.models.upload, verbose_name='附件'),
        ),
    ]
