# Generated by Django 4.2 on 2023-06-26 09:45

from django.db import migrations, models
import mp.workflow.models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_workflow_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='app_group_id',
            field=models.IntegerField(verbose_name='业务组ID'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='app_name',
            field=models.CharField(max_length=100, verbose_name='业务组名称'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='file',
            field=mp.workflow.models.RestrictedFileField(blank=True, null=True, upload_to=mp.workflow.models.upload, verbose_name='附件'),
        ),
    ]
