# Generated by Django 4.2 on 2023-06-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_alter_workflow_app_group_id_alter_workflow_app_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='finish_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结束时间'),
        ),
    ]
