# Generated by Django 4.2 on 2023-06-28 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_workflow_finish_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowaudit',
            name='audit_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
