# Generated by Django 4.2 on 2023-06-29 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0006_alter_workflowaudit_audit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='work_type',
            field=models.SmallIntegerField(choices=[(0, '自动更新'), (1, '业务上线'), (2, '问题排查'), (3, '漏洞修复'), (4, '系统优化'), (5, '应用更新'), (6, 'ansible 更新资产'), (7, 'ansible 模块执行'), (8, 'ansible playbook 执行')], verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='workflowaudit',
            name='workflow_type',
            field=models.SmallIntegerField(choices=[(0, '自动更新'), (1, '业务上线'), (2, '问题排查'), (3, '漏洞修复'), (4, '系统优化'), (5, '应用更新'), (6, 'ansible 更新资产'), (7, 'ansible 模块执行'), (8, 'ansible playbook 执行')], verbose_name='审批类型'),
        ),
        migrations.AlterField(
            model_name='workflowauditlog',
            name='workflow_type',
            field=models.IntegerField(choices=[(0, '自动更新'), (1, '业务上线'), (2, '问题排查'), (3, '漏洞修复'), (4, '系统优化'), (5, '应用更新'), (6, 'ansible 更新资产'), (7, 'ansible 模块执行'), (8, 'ansible playbook 执行')], verbose_name='申请类型'),
        ),
    ]
