# Generated by Django 4.2 on 2023-06-29 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0007_alter_workflow_work_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='work_type',
            field=models.SmallIntegerField(choices=[(0, '自动更新资产信息'), (1, '业务上线'), (2, '问题排查'), (3, '漏洞修复'), (4, '系统优化'), (5, '应用更新')], verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='workflowaudit',
            name='workflow_type',
            field=models.SmallIntegerField(choices=[(0, '自动更新资产信息'), (1, '业务上线'), (2, '问题排查'), (3, '漏洞修复'), (4, '系统优化'), (5, '应用更新')], verbose_name='审批类型'),
        ),
        migrations.AlterField(
            model_name='workflowauditlog',
            name='workflow_type',
            field=models.IntegerField(choices=[(0, '自动更新资产信息'), (1, '业务上线'), (2, '问题排查'), (3, '漏洞修复'), (4, '系统优化'), (5, '应用更新')], verbose_name='申请类型'),
        ),
    ]
