# Generated by Django 4.2 on 2023-06-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0008_alter_workflow_work_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='work_status',
            field=models.CharField(choices=[('finish', '正常结束'), ('abort', '终止流程'), ('manreviewing', '等待审核'), ('review_pass', '审核通过'), ('timingtask', '定时执行'), ('queuing', '排队中'), ('executing', '执行中'), ('autoreviewwrong', '自动执行错误'), ('exception', '执行异常')], max_length=50, verbose_name='状态'),
        ),
    ]
