# Generated by Django 4.2 on 2023-06-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0009_alter_workflow_work_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowlog',
            name='operation_type',
            field=models.SmallIntegerField(choices=[(0, '提交/待审核'), (1, '审核通过'), (2, '审核不通过'), (3, '取消工单'), (4, '定时执行'), (5, '执行工单'), (6, '执行结束')], verbose_name='操作类型'),
        ),
    ]
