# Generated by Django 4.2 on 2023-06-16 10:00

from django.db import migrations, models
import mirage.fields


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sshuser',
            name='become',
            field=models.BooleanField(default=False, verbose_name='become'),
        ),
        migrations.AddField(
            model_name='sshuser',
            name='become_method',
            field=models.CharField(blank=True, default='sudo', max_length=10, null=True, verbose_name='become 方法'),
        ),
        migrations.AddField(
            model_name='sshuser',
            name='become_pass',
            field=mirage.fields.EncryptedCharField(blank=True, default='', max_length=100, null=True, verbose_name='become 密码'),
        ),
        migrations.AddField(
            model_name='sshuser',
            name='become_user',
            field=models.CharField(blank=True, default='root', max_length=20, null=True, verbose_name='become 用户'),
        ),
    ]
